import Link from "next/link"

export default function UserAgreementPage() {
  return (
    <div className="min-h-screen bg-gray-50">
      <header className="bg-white shadow-sm">
        <div className="max-w-7xl mx-auto px-4 py-6 sm:px-6 lg:px-8">
          <div className="flex justify-between items-center">
            <h1 className="text-3xl font-bold text-gray-900">User Agreement</h1>
            <Link href="/" className="text-blue-600 hover:text-blue-800">
              Back to Home
            </Link>
          </div>
        </div>
      </header>

      <main className="max-w-4xl mx-auto px-4 py-12 sm:px-6 lg:px-8">
        <div className="bg-white shadow overflow-hidden rounded-lg">
          <div className="px-4 py-5 sm:p-6 prose prose-blue max-w-none">
            <p className="text-sm text-gray-500 italic">Effective date: April 8, 2025</p>

            <p>
              This User Agreement (the "Agreement") is a legally binding contract between you ("User," "you," or "your")
              and Trackline Solutions ("Company," "we," "us," or "our"). By accessing or using our Website or ChatGPT
              Plugin, you agree to be bound by this Agreement. If you do not agree with any part of this Agreement,
              please do not use our Website or Plugin.
            </p>

            <ol className="space-y-6">
              <li>
                <h2>Acceptance of Terms</h2>
                <p>
                  By using the Website or Plugin, you agree to comply with and be bound by the terms and conditions of
                  this Agreement. We reserve the right to modify this Agreement at any time. Your continued use of the
                  Website or Plugin after any such modifications shall constitute your consent to such changes.
                </p>
              </li>

              <li>
                <h2>Use of the Service</h2>
                <p>
                  <strong>Eligibility:</strong> You must be at least 18 years old to use the Website or Plugin. By using
                  the Website or Plugin, you represent and warrant that you are at least 18 years old.
                </p>
                <p>
                  <strong>User Responsibilities:</strong> You agree to use the Website and Plugin only for lawful
                  purposes. You are prohibited from:
                </p>
                <ul>
                  <li>Using the Plugin to generate harmful, illegal, or unethical content</li>
                  <li>Attempting to reverse engineer or bypass any security measures of the Plugin</li>
                  <li>Using the Plugin in a way that places excessive load on our servers</li>
                  <li>Sharing your access to the Plugin with unauthorized users</li>
                </ul>
              </li>

              <li>
                <h2>ChatGPT Plugin</h2>
                <p>
                  The PromptMe ChatGPT Plugin ("Plugin") is designed to enhance prompts for better AI interactions. When
                  using the Plugin:
                </p>
                <ul>
                  <li>You retain ownership of your original prompts</li>
                  <li>We do not claim ownership of the enhanced prompts generated by the Plugin</li>
                  <li>You are responsible for how you use the enhanced prompts</li>
                  <li>We reserve the right to modify or discontinue the Plugin at any time</li>
                </ul>
              </li>

              <li>
                <h2>Intellectual Property</h2>
                <p>
                  <strong>Ownership:</strong> All content on the Website, including text, graphics, logos, images, and
                  software, is the property of the Company or its content suppliers and is protected by intellectual
                  property laws.
                </p>
                <p>
                  <strong>License:</strong> The Company grants you a limited, non-exclusive, non-transferable license to
                  access and use the Website and Plugin for personal, non-commercial purposes. You may not reproduce,
                  distribute, modify, or create derivative works from any content on the Website without our express
                  written permission.
                </p>
              </li>

              <li>
                <h2>Disclaimers</h2>
                <p>
                  <strong>No Professional Advice:</strong> The information provided on the Website and through the
                  Plugin is for general informational purposes only and does not constitute professional advice. We do
                  not guarantee the accuracy, completeness, or usefulness of any information or enhanced prompts.
                </p>
                <p>
                  <strong>Limitation of Liability:</strong> To the fullest extent permitted by law, the Company shall
                  not be liable for any indirect, incidental, special, consequential, or punitive damages arising out of
                  or related to your use of the Website or Plugin.
                </p>
              </li>

              <li>
                <h2>Privacy Policy</h2>
                <p>
                  Your use of the Website and Plugin is also governed by our Privacy Policy, which is incorporated into
                  this Agreement by reference. Please review our Privacy Policy to understand our practices regarding
                  the collection and use of your personal information.
                </p>
              </li>

              <li>
                <h2>Termination</h2>
                <p>
                  We reserve the right to terminate or suspend your access to the Website or Plugin at our sole
                  discretion, without notice, for conduct that we believe violates this Agreement or is harmful to other
                  users, us, or third parties, or for any other reason.
                </p>
              </li>

              <li>
                <h2>Governing Law</h2>
                <p>
                  This Agreement shall be governed by and construed in accordance with the laws of the Commonwealth of
                  Massachusetts and those of the United States of America, without regard to its conflict of laws
                  principles.
                </p>
              </li>

              <li>
                <h2>Miscellaneous</h2>
                <p>
                  <strong>Entire Agreement:</strong> This Agreement constitutes the entire agreement between you and the
                  Company regarding your use of the Website and Plugin.
                </p>
                <p>
                  <strong>Severability:</strong> If any provision of this Agreement is found to be invalid or
                  unenforceable, the remaining provisions shall continue in full force and effect.
                </p>
                <p>
                  <strong>Contact Information:</strong> If you have any questions about this Agreement, please contact
                  us at support@trackline-solutions.com.
                </p>
              </li>
            </ol>
          </div>
        </div>
      </main>

      <footer className="bg-white mt-12">
        <div className="max-w-7xl mx-auto py-12 px-4 overflow-hidden sm:px-6 lg:px-8">
          <p className="text-center text-base text-gray-500">&copy; 2025 Trackline Solutions. All rights reserved.</p>
        </div>
      </footer>
    </div>
  )
}
